In [151]:
import pandas as pd
import numpy as np

In [152]:
df = pd.read_csv('E0.csv')

In [153]:
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,05/08/2022,20:00,Crystal Palace,Arsenal,0,2,A,0,1,...,1.76,0.50,2.09,1.84,2.04,1.88,2.09,1.88,2.03,1.85
1,E0,06/08/2022,12:30,Fulham,Liverpool,2,2,D,1,0,...,2.73,1.75,1.90,2.03,1.91,2.02,2.01,2.06,1.89,1.99
2,E0,06/08/2022,15:00,Bournemouth,Aston Villa,2,0,H,1,0,...,1.76,0.50,1.93,2.00,1.93,2.00,1.94,2.04,1.88,2.00
3,E0,06/08/2022,15:00,Leeds,Wolves,2,1,H,1,1,...,1.87,-0.25,2.08,1.85,2.10,1.84,2.14,1.87,2.08,1.81
4,E0,06/08/2022,15:00,Newcastle,Nott'm Forest,2,0,H,0,0,...,1.89,-1.00,1.97,1.96,1.99,1.93,2.19,1.97,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,E0,04/03/2023,15:00,Wolves,Tottenham,1,0,H,0,0,...,1.67,0.25,1.90,2.03,1.90,2.02,1.91,2.08,1.87,1.99
247,E0,04/03/2023,17:30,Southampton,Leicester,1,0,H,1,0,...,1.85,0.00,2.09,1.84,2.12,1.83,2.12,2.06,1.99,1.90
248,E0,05/03/2023,14:00,Nott'm Forest,Everton,2,2,D,1,2,...,1.51,0.00,2.11,1.79,2.13,1.82,2.17,1.85,2.09,1.80
249,E0,05/03/2023,16:30,Liverpool,Man United,7,0,H,1,0,...,2.16,0.00,1.75,2.05,1.77,2.17,1.92,2.20,1.79,2.10
250,E0,06/03/2023,20:00,Brentford,Fulham,3,2,H,1,1,...,1.84,-0.50,2.07,1.86,2.08,1.86,2.08,1.89,2.05,1.84

In [154]:
df = df[['HomeTeam','AwayTeam','FTR','B365H', 'B365D', 'B365A']]

In [155]:
df

           HomeTeam       AwayTeam FTR  B365H  B365D  B365A
0    Crystal Palace        Arsenal   A   4.20    3.6   1.85
1            Fulham      Liverpool   D  11.00    6.0   1.25
2       Bournemouth    Aston Villa   H   3.75    3.5   2.00
3             Leeds         Wolves   H   2.25    3.4   3.20
4         Newcastle  Nott'm Forest   H   1.66    3.8   5.25
..              ...            ...  ..    ...    ...    ...
246          Wolves      Tottenham   H   3.30    3.4   2.20
247     Southampton      Leicester   H   2.75    3.3   2.60
248   Nott'm Forest        Everton   D   2.70    3.0   2.88
249       Liverpool     Man United   H   2.38    3.6   2.88
250       Brentford         Fulham   H   1.95    3.6   3.75

[251 rows x 6 columns]

In [156]:
df['New'] = df.apply(lambda x: x['B365H'] if x['B365H'] <= x['B365A'] else 'underdog', axis=1)

C:\Users\hask777\AppData\Local\Temp\ipykernel_1568\1489576516.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['New'] = df.apply(lambda x: x['B365H'] if x['B365H'] <= x['B365A'] else 'underdog', axis=1)

In [157]:
df

           HomeTeam       AwayTeam FTR  B365H  B365D  B365A       New
0    Crystal Palace        Arsenal   A   4.20    3.6   1.85  underdog
1            Fulham      Liverpool   D  11.00    6.0   1.25  underdog
2       Bournemouth    Aston Villa   H   3.75    3.5   2.00  underdog
3             Leeds         Wolves   H   2.25    3.4   3.20      2.25
4         Newcastle  Nott'm Forest   H   1.66    3.8   5.25      1.66
..              ...            ...  ..    ...    ...    ...       ...
246          Wolves      Tottenham   H   3.30    3.4   2.20  underdog
247     Southampton      Leicester   H   2.75    3.3   2.60  underdog
248   Nott'm Forest        Everton   D   2.70    3.0   2.88       2.7
249       Liverpool     Man United   H   2.38    3.6   2.88      2.38
250       Brentford         Fulham   H   1.95    3.6   3.75      1.95

[251 rows x 7 columns]

In [158]:
fa_h = df.copy()

In [159]:
fa_h = fa_h.loc[(fa_h['New'] != 'underdog') & (fa_h['FTR'] == 'H')]

In [160]:
fa_h

        HomeTeam        AwayTeam FTR  B365H  B365D  B365A   New
3          Leeds          Wolves   H   2.25   3.40   3.20  2.25
4      Newcastle   Nott'm Forest   H   1.66   3.80   5.25  1.66
5      Tottenham     Southampton   H   1.33   5.50   8.50  1.33
10   Aston Villa         Everton   H   1.80   3.50   4.75   1.8
11       Arsenal       Leicester   H   1.53   4.33   5.75  1.53
..           ...             ...  ..    ...    ...    ...   ...
243  Aston Villa  Crystal Palace   H   2.05   3.30   3.80  2.05
244     Brighton        West Ham   H   1.80   3.60   4.50   1.8
245      Chelsea           Leeds   H   1.62   4.00   5.50  1.62
249    Liverpool      Man United   H   2.38   3.60   2.88  2.38
250    Brentford          Fulham   H   1.95   3.60   3.75  1.95

[92 rows x 7 columns]

In [161]:
fas = fa_h['B365H'].sum()

In [162]:
fas

158.17000000000002

In [163]:
fa_a = df.copy()

In [164]:
fa_a = fa_a.loc[(fa_a['New'] != 'underdog') & (fa_a['FTR'] == 'A')]

In [165]:
fa_a

           HomeTeam        AwayTeam FTR  B365H  B365D  B365A   New
8        Man United        Brighton   A   1.60   4.20   5.25   1.6
24        Leicester     Southampton   A   1.83   4.00   4.00  1.83
27         West Ham        Brighton   A   2.30   3.40   3.10   2.3
37      Aston Villa        West Ham   A   2.30   3.40   3.10   2.3
54    Nott'm Forest     Bournemouth   A   1.95   3.50   3.80  1.95
72      Southampton         Everton   A   2.15   3.40   3.40  2.15
99      Bournemouth     Southampton   A   2.62   3.30   2.62  2.62
111           Leeds          Fulham   A   2.05   3.50   3.60  2.05
113          Wolves       Leicester   A   2.25   3.25   3.25  2.25
114       Tottenham       Newcastle   A   2.05   3.50   3.50  2.05
123       Liverpool           Leeds   A   1.30   6.00   9.00   1.3
130         Everton       Leicester   A   2.40   3.30   3.00   2.4
131         Chelsea         Arsenal   A   2.55   3.40   2.70  2.55
134        West Ham  Crystal Palace   A   1.90   3.40   4.20   1.9
136        Man City       Brentford   A   1.14   8.00  17.00  1.14
141        West Ham       Leicester   A   2.05   3.40   3.75  2.05
144        Brighton     Aston Villa   A   1.83   3.75   4.20  1.83
147  Crystal Palace          Fulham   A   2.05   3.60   3.50  2.05
148         Everton          Wolves   A   2.30   3.25   3.20   2.3
156        West Ham       Brentford   A   2.00   3.60   3.60   2.0
164       Tottenham     Aston Villa   A   1.67   4.00   5.00  1.67
169       Leicester          Fulham   A   2.20   3.60   3.10   2.2
171     Southampton   Nott'm Forest   A   2.00   3.50   3.80   2.0
180         Everton     Southampton   A   2.25   3.25   3.30  2.25
201     Aston Villa       Leicester   A   1.95   3.60   3.80  1.95
223        Brighton          Fulham   A   1.65   3.80   5.50  1.65
224         Chelsea     Southampton   A   1.40   4.75   8.50   1.4
227          Wolves     Bournemouth   A   1.67   3.60   6.00  1.67
228       Newcastle       Liverpool   A   2.50   3.50   2.70   2.5
232         Everton     Aston Villa   A   2.50   3.20   3.00   2.5

In [166]:
fas = fa_a['B365H'].sum()

In [167]:
fas

60.41

In [168]:
fa_d = df.copy()

In [169]:
fa_d = fa_d.loc[(fa_d['New'] != 'underdog') & (fa_d['FTR'] == 'D')]

In [170]:
fa_d

           HomeTeam        AwayTeam FTR  B365H  B365D  B365A   New
7         Leicester       Brentford   D   2.00   3.75   3.50   2.0
12         Brighton       Newcastle   D   2.45   3.20   3.00  2.45
14      Southampton           Leeds   D   2.25   3.50   3.10  2.25
15           Wolves          Fulham   D   2.30   3.30   3.20   2.3
18          Chelsea       Tottenham   D   2.25   3.40   3.20  2.25
19        Liverpool  Crystal Palace   D   1.18   6.75  16.00  1.18
22          Everton   Nott'm Forest   D   1.90   3.60   4.00   1.9
31        Brentford         Everton   D   2.00   3.50   3.75   2.0
38           Wolves       Newcastle   D   2.70   3.30   2.70   2.7
40   Crystal Palace       Brentford   D   2.05   3.40   3.60  2.05
43            Leeds         Everton   D   2.15   3.50   3.30  2.15
53        Newcastle  Crystal Palace   D   2.00   3.50   3.75   2.0
63        Newcastle     Bournemouth   D   1.44   4.40   7.50  1.44
71        Liverpool        Brighton   D   1.33   5.25   8.50  1.33
75            Leeds     Aston Villa   D   2.35   3.40   3.00  2.35
88        Leicester  Crystal Palace   D   2.30   3.40   3.10   2.3
89           Fulham     Bournemouth   D   1.85   3.75   4.00  1.85
94       Man United       Newcastle   D   1.95   3.80   3.50  1.95
97         Brighton   Nott'm Forest   D   1.40   4.75   7.00   1.4
109         Chelsea      Man United   D   2.05   3.50   3.50  2.05
118       Brentford          Wolves   D   2.20   3.40   3.30   2.2
122          Fulham         Everton   D   2.37   3.40   3.00  2.37
161        Man City         Everton   D   1.13   9.00  19.00  1.13
162       Newcastle           Leeds   D   1.45   4.50   7.00  1.45
167         Arsenal       Newcastle   D   1.80   3.80   4.33   1.8
172           Leeds        West Ham   D   2.60   3.50   2.60   2.6
173     Aston Villa          Wolves   D   1.95   3.60   4.00  1.95
189       Liverpool         Chelsea   D   1.85   3.75   4.00  1.85
190     Bournemouth   Nott'm Forest   D   2.75   3.10   2.75  2.75
195           Leeds       Brentford   D   2.38   3.60   2.88  2.38
199         Chelsea          Fulham   D   1.62   4.00   5.25  1.62
206       Newcastle        West Ham   D   1.60   3.80   6.00   1.6
209      Man United           Leeds   D   1.45   5.00   6.00  1.45
211         Arsenal       Brentford   D   1.44   4.75   7.00  1.44
222       Brentford  Crystal Palace   D   1.83   3.50   4.50  1.83
231          Fulham          Wolves   D   2.50   3.20   3.00   2.5
248   Nott'm Forest         Everton   D   2.70   3.00   2.88   2.7

In [171]:
fad = fa_d['B365D'].sum()

In [172]:
fad

145.85